/**
 * The cipher's S-box: a fixed, non-secret substitution table (confusion technique #2).
 *
 * This is a random permutation of 0..255, generated once with a seeded shuffle
 * (see scripts/generate-sbox.mjs) and hardcoded here as a constant — the same way
 * AES hardcodes its S-box, except AES's table is mathematically constructed for
 * resistance to differential/linear cryptanalysis, while this one is just a random
 * permutation. That's an intentional, documented limitation of this educational
 * cipher (see SECURITY.md): it gets non-linearity, but not proven cryptanalytic
 * resistance.
 *
 * Per Kerckhoffs's principle, the S-box is public — the same table is used for
 * every encryption, and security must rest on the secrecy of the key alone.
 *
 * Generated by scripts/generate-sbox.mjs with SEED = 51981410029
 */
export const SBOX: readonly number[] = [
  92, 99, 132, 96, 73, 35, 15, 198, 223, 63, 130, 60, 254, 172, 218, 74,
  47, 194, 191, 159, 4, 167, 180, 11, 231, 105, 216, 70, 89, 131, 116, 252,
  53, 163, 151, 55, 97, 196, 174, 197, 79, 72, 16, 241, 100, 66, 154, 71,
  83, 150, 13, 3, 77, 52, 28, 113, 192, 239, 123, 93, 144, 200, 153, 125,
  227, 173, 56, 161, 225, 25, 246, 120, 112, 145, 44, 143, 175, 222, 106, 147,
  27, 124, 103, 204, 134, 118, 184, 57, 233, 177, 32, 201, 0, 45, 171, 22,
  169, 162, 170, 26, 183, 160, 228, 127, 195, 24, 42, 39, 185, 250, 58, 111,
  64, 149, 20, 236, 37, 115, 166, 155, 217, 61, 85, 29, 101, 244, 23, 14,
  245, 121, 203, 136, 19, 17, 189, 220, 54, 91, 211, 122, 107, 156, 202, 235,
  36, 187, 251, 81, 208, 94, 248, 224, 119, 133, 213, 7, 190, 38, 2, 46,
  129, 140, 146, 157, 188, 234, 138, 50, 10, 238, 152, 126, 240, 6, 176, 182,
  62, 212, 82, 117, 84, 65, 102, 41, 165, 215, 51, 80, 95, 206, 68, 109,
  8, 205, 76, 104, 90, 141, 242, 207, 9, 255, 48, 135, 249, 229, 137, 158,
  210, 5, 214, 49, 179, 128, 88, 209, 21, 193, 178, 86, 33, 186, 12, 247,
  67, 110, 253, 43, 139, 30, 40, 108, 164, 232, 18, 230, 237, 78, 114, 87,
  69, 221, 168, 98, 1, 34, 226, 243, 181, 31, 148, 75, 59, 142, 219, 199,
];

/** Inverse S-box, derived once at module load: INV_SBOX[SBOX[i]] = i. */
export const INV_SBOX: readonly number[] = (() => {
  const inv = new Array<number>(256);
  for (let i = 0; i < 256; i++) {
    inv[SBOX[i]] = i;
  }
  return inv;
})();
