// One-off generator for the cipher's S-box. Run manually (`node scripts/generate-sbox.mjs`)
// and paste the printed array into src/sbox.ts — the S-box is a fixed constant of the
// algorithm, not something recomputed at runtime (see src/sbox.ts for why).
//
// Uses a seeded PRNG (mulberry32) + Fisher-Yates shuffle so the permutation is
// reproducible from the seed alone, without depending on any crypto library.

const SEED = 0xc1a55_5eed;

function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function generateSBox(seed) {
  const rand = mulberry32(seed);
  const box = Array.from({ length: 256 }, (_, i) => i);
  for (let i = box.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [box[i], box[j]] = [box[j], box[i]];
  }
  return box;
}

const sbox = generateSBox(SEED);

const rows = [];
for (let i = 0; i < 256; i += 16) {
  rows.push('  ' + sbox.slice(i, i + 16).join(', ') + ',');
}
console.log(`// Generated by scripts/generate-sbox.mjs with SEED = ${SEED}\nexport const SBOX: readonly number[] = [\n${rows.join('\n')}\n];`);
